services:
  - type: web
    name: zeril-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python zeril_bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: HUGGINGFACE_TOKEN
        sync: false
